build: use `std::string_view` instead of `absl::string_view`
What
===

use C++ standard `std::string_view` instead of abseil-cpp `absl::string_view`.

Why
===

Abseil LTS 20230802 split `absl::string_view`.

[Release Abseil LTS branch, Aug 2023 · abseil/abseil-cpp](https://github.com/abseil/abseil-cpp/releases/tag/20230802.0)

This I think is a breaking change.
In fact, it is confusing in the following ways,

[912776 – app-i18n/mozc-2.28.5029.102: error: undefined reference to symbol '_ZNK4absl12lts_2023080211string_view4findES1_m](https://bugs.gentoo.org/912776)

I could add a dependency, but it would be complicated if it diverged depending on the version of abseil.
I found it less appropriate that mozc uses abseil's `string_view` instead of C++'s standard library `string_view`.
This is because `string_view` is implemented in C++17 and mozc assumes C++17 as you can see below.

<https://github.com/google/mozc/blob/7ec01d6403fd5e32d71a09fe17ab1f00c9571317/src/.bazelrc#L6>

How
===

I run it command.

~~~console
sed -i 's/#include "absl\/strings\/string_view.h"/#include <string_view>' src/**/*{.h,cc,mm}
~~~

~~~console
sed -i 's/absl::string_view/std::string_view/' src/**/*{.h,cc,mm}
~~~